S02 header
WildCodeSchool-2024-02/JS-bdx-0224-P3-Wildy_gamy pull request #10
Opened 2024-06-15 17:54 UTC by FGAT3

2024-06-16 10:55 UTC, pjroggy approved these changes

2024-06-16 17:02 UTC, PaulBOURY approved these changes

2024-06-17 13:16 UTC, KevinDavoust commented on client/src/components/Header/Header.jsx
> +          className={`nav-link ${isActive("/catalogue") ? "active" : ""}`}
un composant NavLink serait plus approprié et éviterait l'ajout d'une classe sur chaque élément

2024-06-17 13:16 UTC, Elea641 requested changes

2024-06-17 13:16 UTC, Elea641 commented on client/src/components/Header/Header.jsx
> +import { Link, useLocation } from "react-router-dom";
deux composants avec un comportement identique entre Hearder.jsx et NavBar.jsx

2024-06-17 13:16 UTC, Elea641 commented on client/src/components/Header/Header.jsx
> +import "./Header.scss";
Préférer garder la logique dans Header.jsx et passer en props à Navbar

2024-06-17 13:16 UTC, Elea641 commented on server/app/config.js
> +
Modifier les cors afin de n'avoir que les noms de domaine voulus

2024-06-19 08:24 UTC, Yoann-Fortin requested changes

2024-06-19 08:24 UTC, Yoann-Fortin commented on client/src/components/Header/Header.jsx
Why have 2 different navigation bars with the same code?

2024-06-19 08:24 UTC, Yoann-Fortin commented on client/src/components/Header/Header.scss
Why are there so many unused css classes in your component?

2024-06-19 08:24 UTC, Yoann-Fortin commented on client/src/components/NavBar/NavBar.jsx
Same comment as above

2024-06-19 08:24 UTC, Yoann-Fortin commented on client/src/components/NavBar/NavBar.scss
Why are there so many unused css classes in your component?

2024-06-19 08:24 UTC, Yoann-Fortin commented on client/src/data/navLinks.json
Confusing folder name

2024-06-24 08:25 UTC, Yoann-Fortin requested changes

2024-06-24 08:25 UTC, Yoann-Fortin commented on server/app/config.js
> +app.use(cors());
This line can be destroyed since the horns are defined lower down.

2024-06-24 08:25 UTC, Yoann-Fortin commented on client/src/components/Header/Header.scss
Animations should be disabled according to user preference. A css media query is available for this purpose.

2024-06-24 14:24 UTC, Yoann-Fortin requested changes

2024-06-24 14:24 UTC, Yoann-Fortin commented on client/src/components/Header/Header.scss
> +              @media (prefers-reduced-motion: reduce) {
Dead code

2024-06-24 14:24 UTC, Yoann-Fortin commented on client/src/components/Header/Header.scss
> +              @media (prefers-reduced-motion: reduce) {
Same

2024-06-24 14:24 UTC, Yoann-Fortin commented on client/src/components/Header/Header.scss
> +  @media (prefers-reduced-motion: reduce) {
Same

2024-06-24 14:24 UTC, Yoann-Fortin commented on client/src/components/Header/Header.scss
> +    @media (prefers-reduced-motion: reduce) {
Same

2024-06-24 14:24 UTC, Yoann-Fortin commented on client/src/components/Header/Header.scss
> +    @media (prefers-reduced-motion: reduce) {
Same

2024-06-25 07:06 UTC, Yoann-Fortin approved these changes

2024-06-25 07:06 UTC, merged