S02 us1 homepage third section without the desktop version
WildCodeSchool-2024-02/JS-bdx-0224-P3-Wildy_gamy pull request #23
Opened 2024-06-24 14:06 UTC by PaulBOURY

2024-06-24 14:32 UTC, FGAT3 commented on client/src/pages/HomePage/HomePage.jsx
> +      <PodiumGoldCard classeName="podiumGoldCard" card={goldImages} />
change component name and map on your images

2024-06-24 14:32 UTC, FGAT3 commented on client/src/pages/HomePage/HomePage.jsx
> +      <PodiumGoldCard classeName="podiumSilverCard" card={silverImages} />
Same

2024-06-24 14:32 UTC, FGAT3 commented on client/src/pages/HomePage/HomePage.jsx
> +      <PodiumGoldCard classeName="podiumBronzeCard" card={bronzeImages} />
Same

2024-06-24 14:48 UTC, FGAT3 approved these changes
Good job on this section

2024-06-24 14:54 UTC, JadeJolivet approved these changes

2024-06-25 07:44 UTC, KevinDavoust requested changes

2024-06-25 07:44 UTC, KevinDavoust commented on client/src/components/Podiumcard/PodiumCard.jsx
> +    </figure>
mauvais html, fais 2 balises figure

2024-06-25 07:44 UTC, KevinDavoust commented on client/src/components/Podiumcard/PodiumCard.scss
> +  align-items: center;
propriété inutile

2024-06-25 07:44 UTC, KevinDavoust commented on client/src/pages/HomePage/HomePage.jsx
> +      <PodiumCard key={podiumImage} card={podiumImage} />
indentation

2024-06-25 11:07 UTC, KevinDavoust commented on client/src/components/Podiumcard/PodiumCard.jsx
> +      </figure>
mauvais html

2024-06-25 13:47 UTC, PaulBOURY commented on client/src/components/Podiumcard/PodiumCard.jsx
> +      </figure>
il n'y a plus qu'un seul figcaption donc une seule balise figure suffit non?

2024-06-25 14:10 UTC, KevinDavoust approved these changes

2024-06-25 14:11 UTC, KevinDavoust approved these changes

2024-06-25 14:23 UTC, merged