S02 footer about us
WildCodeSchool-2024-02/JS-bdx-0224-P3-Wildy_gamy pull request #29
Opened 2024-06-25 18:26 UTC by FGAT3

2024-06-25 19:43 UTC, pjroggy approved these changes

2024-06-26 12:30 UTC, JadeJolivet approved these changes

2024-07-01 14:40 UTC, Yoann-Fortin requested changes

2024-07-01 14:40 UTC, Yoann-Fortin commented on client/src/App.jsx
A dedicated file would be better

2024-07-01 14:40 UTC, Yoann-Fortin commented on client/src/components/GameListModal/GameListModal.jsx
Props cannot be both optional and required

2024-07-01 14:40 UTC, Yoann-Fortin commented on client/src/components/NavigationChevron/NavigationChevron.jsx
Separates logic from semantics

2024-07-01 14:40 UTC, Yoann-Fortin commented on client/src/pages/GameListPage/GameListPage.jsx
Fill in only the necessary props

2024-07-08 07:37 UTC, Yoann-Fortin requested changes

2024-07-08 07:37 UTC, Yoann-Fortin commented on client/src/components/ChevronButton/ChevronButton.jsx
> +      aria-label={ariaLabel}
If you have a decorative image, take advantage of the opportunity to specify the button's function in the alt attribute of the image contained in the button.

2024-07-08 10:17 UTC, Yoann-Fortin approved these changes

2024-07-08 10:17 UTC, merged