add connexion and login page merge dev in main
WildCodeSchool-2024-02/JS-bdx-0224-P3-Wildy_gamy pull request #36
Opened 2024-07-01 14:53 UTC by pjroggy

2024-07-08 07:36 UTC, FGAT3 approved these changes
Seems good to me

2024-07-08 07:41 UTC, PaulBOURY approved these changes

2024-07-08 12:06 UTC, FGAT3 approved these changes

2024-07-08 12:09 UTC, JadeJolivet approved these changes

2024-07-08 13:14 UTC, Yoann-Fortin requested changes

2024-07-08 13:14 UTC, Yoann-Fortin commented on client/src/components/FlipCard/FlipCard.scss
> +    box-sizing: border-box;
repeated code

2024-07-08 13:14 UTC, Yoann-Fortin commented on client/src/pages/LoginPage/LoginPage.jsx
> +          aria-label="Se connecter"
repeated code with content in this node

2024-07-08 13:14 UTC, Yoann-Fortin commented on client/src/pages/RegistrationPage/RegistrationPage.jsx
> +          aria-label="validation"
same comment

2024-07-08 13:14 UTC, Yoann-Fortin commented on server/app/middleware/authActions.js
This middleware has three reasons to change: it needs to be refactored into two middleswares and the controller needs to be left alone.

2024-07-08 13:14 UTC, Yoann-Fortin commented on server/app/routers/api/router.js
Missing another middleware and controller with specific method

2024-07-08 13:14 UTC, Yoann-Fortin commented on server/database/models/UserRepository.js
> +        created_at,
dead code because your database already know a specific method to affect a correct date

2024-07-09 10:03 UTC, Yoann-Fortin approved these changes

2024-07-09 10:03 UTC, merged