S02 us4 reward page
WildCodeSchool-2024-02/JS-bdx-0224-P3-Wildy_gamy pull request #37
Opened 2024-07-01 18:16 UTC by FGAT3

2024-07-02 07:46 UTC, PaulBOURY approved these changes
gg !

2024-07-08 07:38 UTC, pjroggy approved these changes

2024-07-08 07:49 UTC, KevinDavoust requested changes

2024-07-08 07:49 UTC, KevinDavoust commented on server/app/routers/api/router.js
> +const { hashPassword } = require("../../middelware/hashPassword");
petite faute, middelware au lieu de middleware

2024-07-08 07:49 UTC, KevinDavoust commented on server/database/tables.js
> +tables.item = new RewardRepository();
le nom de la table c'est reward, pas item

2024-07-08 08:22 UTC, merged