S05 us18 user page score
WildCodeSchool-2024-02/JS-bdx-0224-P3-Wildy_gamy pull request #38
Opened 2024-07-02 13:53 UTC by PaulBOURY

2024-07-02 14:10 UTC, JadeJolivet approved these changes

2024-07-02 15:29 UTC, FGAT3 commented on client/src/components/ModifyInfoModale/ModifyInfoModale.jsx
Need to be refacto with PJ's form

2024-07-02 15:29 UTC, FGAT3 commented on client/src/components/ModifyInfoModale/ModifyInfoModale.scss
> +    padding: 0.25rem 1rem;
Need to uniformize all buttons

2024-07-02 15:29 UTC, FGAT3 commented on client/src/components/ScoreDisplay/ScoreDisplay.jsx
> +    <p className="scoreDisplay"> 2000 points</p>
1 p or 2 p ? To be or not to be ?

2024-07-02 15:29 UTC, FGAT3 commented on client/src/pages/ProfilePage/ProfilePage.jsx
> +  const openModal = (gameName) => {
create file for this function and import it

2024-07-02 15:29 UTC, FGAT3 commented on client/src/pages/ProfilePage/ProfilePage.jsx
> +    setSelectedGame({
this should be a parameter for refacto

2024-07-08 15:13 UTC, FGAT3 approved these changes

2024-07-09 09:59 UTC, JadeJolivet approved these changes

2024-07-09 11:55 UTC, Yoann-Fortin requested changes

2024-07-09 11:55 UTC, Yoann-Fortin commented on client/src/components/ScoreDisplay/ScoreDisplay.jsx
You can see this page to implement an accessible table : https://www.w3.org/WAI/tutorials/tables/

2024-07-09 11:55 UTC, Yoann-Fortin commented on client/src/pages/ProfilePage/ProfilePage.jsx
> +  const [showModal, setShowModal] = useState(false);
group your states please

2024-07-09 11:55 UTC, Yoann-Fortin commented on client/src/pages/ProfilePage/ProfilePage.jsx
> +  const openModalModify = () => setShowModalModify(true);
you duplicate same logic, a function more generic with an inversion of state would be better

2024-07-09 11:55 UTC, Yoann-Fortin commented on client/src/pages/ProfilePage/ProfilePage.jsx
> +      <h1>Profile</h1>
extract your semantic in another component please

2024-07-09 15:07 UTC, merged