DemoPage backend score in party table
WildCodeSchool-2024-02/JS-bdx-0224-P3-Wildy_gamy pull request #43
Opened 2024-07-09 14:47 UTC by JadeJolivet

2024-07-09 14:57 UTC, PaulBOURY approved these changes

2024-07-10 12:14 UTC, FGAT3 commented on client/src/pages/DemoPage/DemoPage.jsx
> +    <main className="background">
background is too generic and could be used in other page so maybe more something like "bg-demo-page"

2024-07-10 12:14 UTC, FGAT3 commented on client/src/pages/DemoPage/demoPage.scss
> +@media (max-width: 768px) {
better putting this css outside of media query and using our mixin "on-desktop-up" (outside of the mixin will be the style for mobile and inside of the mixin the style for desktop)

2024-07-11 07:40 UTC, KevinDavoust requested changes

2024-07-11 07:40 UTC, KevinDavoust commented on client/src/pages/DemoPage/DemoPage.jsx
> +    <main className="bg-demoPage">
nommage mi-camelCase mi-kebab-case 🤨

2024-07-11 08:23 UTC, FGAT3 approved these changes

2024-07-11 10:05 UTC, merged