S05 us25 auth context
WildCodeSchool-2024-02/JS-bdx-0224-P3-Wildy_gamy pull request #45
Opened 2024-07-10 10:19 UTC by pjroggy

2024-07-10 10:22 UTC, PaulBOURY approved these changes

2024-07-10 13:32 UTC, FGAT3 approved these changes
Magnific

2024-07-11 08:01 UTC, KevinDavoust requested changes

2024-07-11 08:01 UTC, KevinDavoust commented on client/src/services/decodeToken.js
> +    console.error("Invalid token", error);
rien dans la console

2024-07-11 08:01 UTC, KevinDavoust commented on server/app/middleware/verifyToken.js
>      console.error(err);
rien dans la console

2024-07-11 09:37 UTC, merged