Dev into main
WildCodeSchool-2024-02/JS-bdx-0224-P3-Wildy_gamy pull request #48
Opened 2024-07-12 07:02 UTC by FGAT3

2024-07-12 07:57 UTC, Yoann-Fortin requested changes

2024-07-12 07:57 UTC, Yoann-Fortin commented on client/src/components/ProfileInfos/ProfileInfos.jsx
> +        aria-label="Ouverture de la modale modifier mes informations"
Useless

2024-07-12 07:57 UTC, Yoann-Fortin commented on client/src/components/ProfileInfos/ProfileInfos.jsx
> +        aria-label="Ouverture de la modale supprimer mes informations"
Useless

2024-07-12 07:57 UTC, Yoann-Fortin commented on client/src/components/ScoreDisplay/ScoreDisplay.jsx
Isn't accessible

2024-07-12 07:57 UTC, Yoann-Fortin commented on client/src/components/ScoreDisplay/ScoreDisplay.scss
> +    display: none;
is removed on DOM to accessibility assistance. Privilegiate visibility hidden or another method to mask this

2024-07-15 08:26 UTC, JadeJolivet approved these changes

2024-07-15 11:54 UTC, Yoann-Fortin approved these changes

2024-07-15 11:54 UTC, merged