avant dernière pr dev dans main
WildCodeSchool-2024-02/JS-bdx-0224-P3-Wildy_gamy pull request #60
Opened 2024-07-16 14:22 UTC by pjroggy

2024-07-16 14:27 UTC, PaulBOURY approved these changes

2024-07-16 15:14 UTC, JadeJolivet approved these changes
square like a watermelon

2024-07-16 15:15 UTC, FGAT3 approved these changes
Square like pasteque

2024-07-17 06:02 UTC, Yoann-Fortin requested changes

2024-07-17 06:02 UTC, Yoann-Fortin commented on client/src/main.jsx
> +      transition:Bounce
Bounce is not imported, are you sure it works?

2024-07-17 07:01 UTC, pjroggy commented on client/src/main.jsx
> +      transition:Bounce
No import it's the setting of the ToastContainer, all import with toastify

2024-07-17 07:40 UTC, Yoann-Fortin approved these changes

2024-07-17 07:40 UTC, merged