S02 us7 game list page
WildCodeSchool-2024-02/JS-bdx-0224-P3-Wildy_gamy pull request #7
Opened 2024-06-13 15:23 UTC by JadeJolivet

2024-06-14 09:34 UTC, PaulBOURY approved these changes

2024-06-14 22:20 UTC, FGAT3 requested changes
Let's use and import the images from the back ;)

I suggest creating global const like :

const BASE_URL = import.meta.env.VITE_API_URL;
const catalog = `${BASE_URL}/catalog`;

And changing your json's image src path to : `catalog/file-name.format`

2024-06-17 13:22 UTC, FGAT3 approved these changes

2024-06-17 13:22 UTC, FGAT3 commented on client/src/pages/GameListPage/GameListPage.scss
> +@import "../../scss/variables.scss";
You only need to import index.scss

2024-06-17 13:22 UTC, FGAT3 commented on client/src/pages/GameListPage/GameListPage.scss
> +@import "../../scss/mixins.scss";
You only need to import index.scss

2024-06-17 13:45 UTC, KevinDavoust requested changes

2024-06-17 13:45 UTC, KevinDavoust commented on client/src/components/GameListModal/GameListModal.jsx
> +        <p>Date de sortie : {game.date_de_sortie}</p>
in english please 👩‍🏫

2024-06-17 13:45 UTC, KevinDavoust commented on client/src/components/GameListModal/GameListModal.jsx
> +  open: PropTypes.bool.isRequired,
si c'est un booleen, plutôt isOpen à la place du verbe qui laisse imaginer une fonction 🤨

2024-06-17 13:45 UTC, KevinDavoust commented on client/src/components/GameListModal/GameListModal.scss
> +  z-index: 999;
mdr

2024-06-17 15:17 UTC, KevinDavoust approved these changes

2024-06-17 15:18 UTC, merged